---
name: Release
run-name: Build ${{ github.ref_name }} by @${{ github.actor }}

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: get tag
        uses: olegtarasov/get-tag@v2.1.2
        id: tagName
        with:
          tagRegex: "(.*)"

      - name: Maven build
        run: ./mvnw -Drevision=${{ env.GIT_TAG_NAME }} clean package

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/jfr-exporter-${{ env.GIT_TAG_NAME }}.jar"
          bodyFile: CHANGELOG.md
